spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/fanmeeting
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
server:
  servlet:
    session:
      tracking-modes: cookie
